### ISSUE TITLE
Fix Keydebouncing.

### ISSUE THREAD

**Issue by geekbozu** [Cemetech/TI-DCC#4]
Currently holding a key then another key. Followed by releasing the original key makes the program assume the original key is still being held.

**Comment by geekbozu** [comment]
Fixed "good enough"

**Comment by KermMartian** [comment]
Exactly the resolution I love to see from a @geekboy1011

**Comment by geekbozu** [comment]
I would rather multikey input but that is a pipedream in the current implementation
